#!/usr/bin/env bash
# Generate openclaw.json from environment variables
# This ensures all configuration values are in sync
#
# Usage:
#   source ../.env  # or set env vars externally
#   ./generate-openclaw-config.sh [output_file]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTENV_FILE="$SCRIPT_DIR/../.env"
OUTPUT_FILE="${1:-$SCRIPT_DIR/openclaw.json}"

# Load .env if exists
if [[ -f "$DOTENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$DOTENV_FILE"
  set +a
  echo "[info] loaded $DOTENV_FILE"
fi

# Default values (fallback if env vars not set)
OPENCLAW_PORT="${OPENCLAW_PORT:-18789}"
OPENCLAW_GATEWAY_TOKEN="${OPENCLAW_GATEWAY_TOKEN:-}"
ROSBRIDGE_PORT="${ROSBRIDGE_PORT:-9090}"
ROSCLAW_TRANSPORT_MODE="${ROSCLAW_TRANSPORT_MODE:-rosbridge}"
ROSCLAW_ROSBRIDGE_URL="${ROSCLAW_ROSBRIDGE_URL:-ws://agiros:$ROSBRIDGE_PORT}"
ROSCLAW_ROBOT_NAME="${ROSCLAW_ROBOT_NAME:-TurtleBot3 (Sim)}"
ROSCLAW_ROBOT_TYPE="${ROSCLAW_ROBOT_TYPE:-turtlebot}"
ROSCLAW_RECONNECT="${ROSCLAW_RECONNECT:-true}"
ROSCLAW_RECONNECT_INTERVAL="${ROSCLAW_RECONNECT_INTERVAL:-3000}"

# Generate token if not provided
if [[ -z "$OPENCLAW_GATEWAY_TOKEN" ]]; then
  OPENCLAW_GATEWAY_TOKEN=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
  echo "[info] generated OPENCLAW_GATEWAY_TOKEN"
fi

# Remove quotes from robot name if present
ROSCLAW_ROBOT_NAME=$(echo "$ROSCLAW_ROBOT_NAME" | tr -d '"')

cat > "$OUTPUT_FILE" <<EOF
// OpenClaw Gateway configuration
// Generated by generate-openclaw-config.sh
//
// Network: agiros service available at ws://agiros:${ROSBRIDGE_PORT}
// Gateway: http://0.0.0.0:${OPENCLAW_PORT}

{
  "gateway": {
    "mode": "local",
    "port": ${OPENCLAW_PORT},
    "bind": "lan",
    "auth": {
      "mode": "token",
      "token": "${OPENCLAW_GATEWAY_TOKEN}"
    }
  },

  "plugins": {
    "enabled": true,
    "allow": ["agirosclaw"],
    "load": {
      "paths": ["/home/node/agirosclaw/extensions/openclaw-plugin"]
    },
    "entries": {
      "agirosclaw": {
        "enabled": true,
        "config": {
          "transport": { "mode": "${ROSCLAW_TRANSPORT_MODE}" },
          "rosbridge": {
            "url": "${ROSCLAW_ROSBRIDGE_URL}",
            "reconnect": ${ROSCLAW_RECONNECT},
            "reconnectInterval": ${ROSCLAW_RECONNECT_INTERVAL}
          },
          "robot": { "name": "${ROSCLAW_ROBOT_NAME}", "type": "${ROSCLAW_ROBOT_TYPE}" }
        }
      }
    }
  },

  "agents": {
    "defaults": {
      "workspace": "~/.openclaw/workspace"
    }
  }
}
EOF

echo "[ok] generated $OUTPUT_FILE"
echo "[info] OPENCLAW_GATEWAY_TOKEN=$OPENCLAW_GATEWAY_TOKEN"
